language: node_js
node_js:
- '4.1'
script: bash ./deploy.sh
branches:
  only:
  - gh-pages
cache:
  directories:
  - node_modules
env:
  global:
    GH_REF: github.com/thibthib/duple.git
    secure: UxKGII5H0fyiFzaZ+WAzAuQHZaoLykV73IL4VpWW3ZBdWIuUCZUzRA3/FEwn1ElZXoudfBr5/z9s1fvbdJarpkdiaOXL/tCSFtle4Sa7IjPU3sbFKM2+CSEPqsgGQrWTLrgJq3s2DJlOHKTaHy++BQfU4vCEbQQmoViHM5HOJDlwJ4nQJS95CQ3/6VtohHYpkU4DyW5OtbpwpF5kg29jCthmstuClUblu4ysws0Cz2zJ4eQReBEj5HHFdZfngIUXp8NmyQR7BZQvpjgxV7+CF1XwwjPAmwTcpFG0FHyGFBDJ75DPUfMpkGgrSwHiDy+L052a/qNZlPyce9sWh77TrWx2aEWX4rETfrDStQJ+6GIw7rayyhPZwk0VcV1kKeIlm1ZiZ2sdQisEsqM266GdI1F0pUA1AEizFI0G7w0PoNtOlRBzU9O/+ILl4lrUcrJfoLkDl/eW0l+5+zZUYyE7tte9XW4CAAgXQufTY4ismBygiGZ4B+q8X483Fy+V8G7tAQtTZL6VR/xIlevc8O9qgPoljOtJepIufDht+bi2nQsj1RaDLK3FvWes7PJHEE5ku9/SIFw5bO1NE9ZdHdzDkstlyz8RSUI0z36/N24CP8sSbow6C/EbOWR2iSUR+wmDsfXaxxQonq8SwHD03vYpc8Zsg1WlzQjMhOD0DuClh9U=
